version: '3.3'

networks:
  rest_test_default:
    driver: bridge

services:
  web-service:
    build:
      context: .
      dockerfile: Dockerfile.server
    ports:
      - "5000:5000"
    networks:
      - rest_test_default

  client:
    build:
      context: .
      dockerfile: Dockerfile.client
    networks:
      - rest_test_default
    depends_on:
      - web-service
